-- Here I was selecting the most recent changes to a given active program

SELECT max(CHG_TMSTMP),
       ACTION_TXT,
       FIELD_NAME_TXT,
       FIELD_VALUE_OLD_TXT,
       FIELD_VALUE_NEW_TXT,
       IDENT_DATA_TXT,
       RE_REG_ENT.REG_ENT_ID,
       RE_REG_ENT.REF_NUM_TXT,
       ADDN_ID,
       ADDN_ID_STATUS_CD,
       PROGRAM_ID
  FROM READM.RE_REG_ENT
       INNER JOIN READM.RE_PGM_INTS
           ON (RE_REG_ENT.REG_ENT_ID = RE_PGM_INTS.REG_ENT_ID)
       INNER JOIN READM.LM_SYS_UNIQ_ID
           ON (RE_PGM_INTS.PGM_INTS_ID = LM_SYS_UNIQ_ID.PGM_INTS_ID)
       INNER JOIN READM.LM_ADDN_ID
           ON (LM_SYS_UNIQ_ID.SYS_UNIQ_ID = LM_ADDN_ID.SYS_UNIQ_ID)
       INNER JOIN READM.LM_LGCY_SYS
           ON (LM_LGCY_SYS.LGCY_SYS_ID = LM_SYS_UNIQ_ID.LGCY_SYS_ID)
       INNER JOIN READM.LM_PGM_LGCY_SYS
           ON (LM_LGCY_SYS.LGCY_SYS_ID = LM_PGM_LGCY_SYS.LGCY_SYS_ID)
       CROSS JOIN AUDIT_ADM.AU_AUDIT_LOG
 WHERE (IDENT_DATA_TXT = CAST (LM_ADDN_ID.ADDN_ID AS VARCHAR2 (60)))
 AND (LM_ADDN_ID.ADDN_ID_STATUS_CD = 'ACTIVE' 
 AND RE_REG_ENT.REG_ENT_ID in (
SELECT RE_REG_ENT.REG_ENT_ID  
FROM RE_REG_ENT
       INNER JOIN READM.RE_PGM_INTS
           ON (RE_REG_ENT.REG_ENT_ID = RE_PGM_INTS.REG_ENT_ID)
       INNER JOIN READM.LM_SYS_UNIQ_ID
           ON (RE_PGM_INTS.PGM_INTS_ID = LM_SYS_UNIQ_ID.PGM_INTS_ID)
       INNER JOIN READM.LM_ADDN_ID
           ON (LM_SYS_UNIQ_ID.SYS_UNIQ_ID = LM_ADDN_ID.SYS_UNIQ_ID)
       INNER JOIN READM.LM_LGCY_SYS
           ON (LM_LGCY_SYS.LGCY_SYS_ID = LM_SYS_UNIQ_ID.LGCY_SYS_ID)
       INNER JOIN READM.LM_PGM_LGCY_SYS
           ON (LM_LGCY_SYS.LGCY_SYS_ID = LM_PGM_LGCY_SYS.LGCY_SYS_ID)
WHERE LM_PGM_LGCY_SYS.PROGRAM_ID = 875591092000364))
 AND ((FIELD_NAME_TXT = 'ALT_REG_ENT_NAME'
 AND ACTION_TXT = 'UPDATE')
 or (FIELD_NAME_TXT = 'REG_ENT_NAME'
 AND ACTION_TXT = 'UPDATE'))
 GROUP BY RE_REG_ENT.REG_ENT_ID, RE_REG_ENT.REF_NUM_TXT, IDENT_DATA_TXT, ADDN_ID, ADDN_ID_STATUS_CD,
       PROGRAM_ID, ACTION_TXT,
       FIELD_NAME_TXT,
       FIELD_VALUE_OLD_TXT,
       FIELD_VALUE_NEW_TXT;
