-- a query to get the entities that have active sub-entities with two different addresses

SELECT RE_REG_ENT.REF_NUM_TXT, COUNT(RE_GEO_LOC.ADDR_ID), RE_REG_ENT.REG_ENT_NAME, RE_GEO_LOC.ADDR_ID, LM_ADDN_ID.ADDN_ID, LM_ADDN_ID.ADDN_ID_STATUS_CD
FROM RE_REG_ENT, RE_GEO_LOC, LM_ADDN_ID
WHERE RE_REG_ENT.ADDR_ID = RE_GEO_LOC.ADDR_ID
AND RE_GEO_LOC.DENORMALIZED_ID = LM_ADDN_ID.ADDN_ID
AND LM_ADDN_ID.ADDN_ID_STATUS_CD = 'ACTIVE'
GROUP BY RE_REG_ENT.REF_NUM_TXT, RE_REG_ENT.REG_ENT_NAME, RE_GEO_LOC.ADDR_ID, LM_ADDN_ID.ADDN_ID, LM_ADDN_ID.ADDN_ID_STATUS_CD
HAVING COUNT(RE_GEO_LOC.ADDR_ID) > 1;
